[package]
name = "chip8"
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lazy_static = "1.4.0"
winit = "0.26"
pixels = "0.3"

[features]
debug = []